export const config = {
  bindto: '#chart',
  size_width: undefined,
  size_height: undefined,
  font_size: 12,
  font_color: '#000',
  data_json: [],
  data_type: 'map',
  data_row_categories: [],
  data_row_aggressions: [],
  data_column_categories: [],
  data_column_aggressions: [],
  data_sized_feature: undefined,
  data_colored_feature: undefined,
  data_colored_type: undefined, //linear or ordinal
  data_labeled: [], //['sum(sales)', 'sum(profits)']
  data_range_color: [],
  data_range_size: [],
  color_schemes: [],
  color_opacity: [],
  table_outter_color: '#ccc',
  table_outter_width: 1,
  table_inner_color: '#ccc',
  table_inner_width: 1,
  table_padding_top: 0,
  table_padding_left: 0,
  table_padding_bottom: 0,
  table_padding_right: 0,
  table_header_top_height: 35,
  table_header_left_width: 100,
  table_header_auto: false,
  table_body_width: 400,
  table_body_height: 400,
  tooltip_show: true,
  point_size: 2,
  map_level: undefined,
  map_center: [],
  map_change: null,
}

//module.exports